create table Free_posts (
                                  p_no varchar2(20 char) unique,
                                  p_id varchar2(30 char),
                                  p_name varchar2(20 char) not null,
                                  p_begin varchar2(40 char) not null,
                                  p_title varchar2(200 char) not null,
                                  p_img varchar2(200 char) not null,
                                  p_text varchar2(4000 char) not null,
                                  p_date date not null
);

ALTER TABLE Free_posts
    DROP PRIMARY KEY;



create sequence Free_posts_seq;

SELECT MAX(b_no) FROM Free_posts;

DROP SEQUENCE Free_posts_seq;


insert into Free_posts values (Free_posts_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요' ,'c.jpg','코난이 참 좋아요', sysdate);

select * from Free_posts;

drop table Free_posts;


CREATE TABLE Free_posts_comment (
                                    c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
                                    b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
                                    c_writer VARCHAR2(100) NOT NULL,                       -- 댓글 작성자
                                    c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
                                    c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
                                    FOREIGN KEY (b_no) REFERENCES board_free_table(b_no) ON DELETE CASCADE,
                                    FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence Free_posts_comment_seq;

insert into Free_posts_comment (b_no, c_writer, c_content, c_date)values (223,'호잇이계속되면', '좋은글입니다.', systimestamp);
select * from Free_posts_comment;

drop table Free_posts_comment;
create table User_DB
(
    user_id       varchar2(50 char) primary key,
    user_pw       varchar2(50 char)  not null,
    user_name     varchar2(50 char)  not null,
    user_nickname varchar2(50 char)  not null unique,
    user_email    varchar2(100 char) not null unique,
    user_gender   varchar2(100 char) not null,
    user_image    varchar2(555 char) default null,
    user_date     timestamp          default SYSTIMESTAMP
);

drop table Post_DB cascade constraints purge;

insert into User_DB (user_id, user_pw, user_name, user_nickname, user_email, user_gender, user_image)
values ('user03', 'password03', 'Taro', 'taro_nick03', 'taro03@email.com', 'male', 'profile_image.png');

select *
from User_DB;

ALTER TABLE User_DB
    MODIFY user_date TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul';

SELECT user_date, user_date AT TIME ZONE 'Asia/Seoul'
FROM User_DB;

ALTER TABLE Post_DB
    MODIFY post_date TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul';

ALTER TABLE Post_DB
    MODIFY post_update TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul';



ALTER DATABASE SET TIME_ZONE = 'Asia/Seoul';

CREATE TABLE Post_DB
(
    user_id      varchar2(50 char)  not null,
    user_nickname varchar2(50 char)  not null unique,
    post_begin   varchar2(50 char)  not null,
    post_id      number generated always as identity primary key,
    post_title   varchar2(100 char) not null,
    post_context clob               not null,
    post_image   varchar2(555 char),
    post_date    timestamp default SYSTIMESTAMP,
    post_update  timestamp default SYSTIMESTAMP,
    constraint fk_post_user foreign key (user_id) references User_DB (user_id) ON DELETE CASCADE,
    constraint fk_post_user foreign key (user_nickname) references User_DB (user_nickname)
);

insert into Post_DB (user_id, post_begin, post_title, post_context, post_image, post_date, post_update) VALUES ('11', '서울', '11', '11','11');
/*업데이트 시스데이트 다시 넣기*/

select * from Post_DB;
